import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/header";
import TrendyProductsSection from "./component/slide";
import Discount from "./component/discount";
import TestimonialSlider  from "./component/review";
import Footer from "./component/footer";
import Banner from "@/app/component/banner";
import FirstRowProduct from "@/app/component/firstproduct";
import SecondRow from "@/app/component/secondrow";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <Banner/>
        <FirstRowProduct/>
        <SecondRow/>
        {children}
        <TrendyProductsSection/>
        <Discount/>
        <TestimonialSlider/>
        <Footer/>
      </body>
    </html>
  );
}
